### ISSUE TITLE
Gönderilen Mail Başlığı HK.

### ISSUE THREAD

**Issue by salyangoz** [salyangoz/parasut-rapor#1]
- [ ] Gönderilen mailde başlıklar aşağıdaki şekilde değiştirilsin.

Aylık
Salyangoz Teknoloji A.Ş. Aralık 2016 e-Fatura Listesi
Haftalık
Salyangoz Teknoloji A.Ş. 17-25 Aralık e-Fatura Listesi
Günlük
Salyangoz Teknoloji A.Ş. 17 Aralık 2016 e-Fatura Listesi

**Comment by yedincisenol** [comment]
17 25 aralik manidar olmus :)) peki 30 aralik 1 ocak secerse nasil saapsin?

**Comment by salyangoz** [comment]
Haftalık kısmını şu şekilde revize edebiliriz o halde.
Salyangoz Teknoloji A.Ş. 30 Ara 16 - 01 Oca 17 e-Fatura Listesi
